# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBFusePreferences.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PBFusePreferences.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17PBFusePreferences.proto\"?\n\x11PBFusePreferences\x12*\n\x0bpreferences\x18\x01 \x03(\x0b\x32\x15.PBFuseItemPreference\"\xc4\x01\n\x14PBFuseItemPreference\x12.\n\npreference\x18\x01 \x02(\x0e\x32\x11.PBFusePreference:\x07NEUTRAL\x12\x0f\n\x07\x61\x64\x61m_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x65xternal_id\x18\x03 \x01(\t\x12\x1d\n\x15\x63reated_offset_millis\x18\x04 \x01(\x03\x12\x37\n\x0fpreference_type\x18\x05 \x01(\x0e\x32\x15.PBFusePreferenceType:\x07UNKNOWN*3\n\x10PBFusePreference\x12\x0b\n\x07NEUTRAL\x10\x00\x12\x08\n\x04LOVE\x10\x01\x12\x08\n\x04HATE\x10\x02*W\n\x14PBFusePreferenceType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04SONG\x10\x01\x12\t\n\x05\x41LBUM\x10\x02\x12\x0c\n\x08PLAYLIST\x10.\x12\x0f\n\x0bMUSIC_VIDEO\x10\x05')
)

_PBFUSEPREFERENCE = _descriptor.EnumDescriptor(
  name='PBFusePreference',
  full_name='PBFusePreference',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HATE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=291,
  serialized_end=342,
)
_sym_db.RegisterEnumDescriptor(_PBFUSEPREFERENCE)

PBFusePreference = enum_type_wrapper.EnumTypeWrapper(_PBFUSEPREFERENCE)
_PBFUSEPREFERENCETYPE = _descriptor.EnumDescriptor(
  name='PBFusePreferenceType',
  full_name='PBFusePreferenceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SONG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALBUM', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYLIST', index=3, number=46,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MUSIC_VIDEO', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=344,
  serialized_end=431,
)
_sym_db.RegisterEnumDescriptor(_PBFUSEPREFERENCETYPE)

PBFusePreferenceType = enum_type_wrapper.EnumTypeWrapper(_PBFUSEPREFERENCETYPE)
NEUTRAL = 0
LOVE = 1
HATE = 2
UNKNOWN = 0
SONG = 1
ALBUM = 2
PLAYLIST = 46
MUSIC_VIDEO = 5



_PBFUSEPREFERENCES = _descriptor.Descriptor(
  name='PBFusePreferences',
  full_name='PBFusePreferences',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preferences', full_name='PBFusePreferences.preferences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=90,
)


_PBFUSEITEMPREFERENCE = _descriptor.Descriptor(
  name='PBFuseItemPreference',
  full_name='PBFuseItemPreference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preference', full_name='PBFuseItemPreference.preference', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adam_id', full_name='PBFuseItemPreference.adam_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_id', full_name='PBFuseItemPreference.external_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_offset_millis', full_name='PBFuseItemPreference.created_offset_millis', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preference_type', full_name='PBFuseItemPreference.preference_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=289,
)

_PBFUSEPREFERENCES.fields_by_name['preferences'].message_type = _PBFUSEITEMPREFERENCE
_PBFUSEITEMPREFERENCE.fields_by_name['preference'].enum_type = _PBFUSEPREFERENCE
_PBFUSEITEMPREFERENCE.fields_by_name['preference_type'].enum_type = _PBFUSEPREFERENCETYPE
DESCRIPTOR.message_types_by_name['PBFusePreferences'] = _PBFUSEPREFERENCES
DESCRIPTOR.message_types_by_name['PBFuseItemPreference'] = _PBFUSEITEMPREFERENCE
DESCRIPTOR.enum_types_by_name['PBFusePreference'] = _PBFUSEPREFERENCE
DESCRIPTOR.enum_types_by_name['PBFusePreferenceType'] = _PBFUSEPREFERENCETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBFusePreferences = _reflection.GeneratedProtocolMessageType('PBFusePreferences', (_message.Message,), dict(
  DESCRIPTOR = _PBFUSEPREFERENCES,
  __module__ = 'PBFusePreferences_pb2'
  # @@protoc_insertion_point(class_scope:PBFusePreferences)
  ))
_sym_db.RegisterMessage(PBFusePreferences)

PBFuseItemPreference = _reflection.GeneratedProtocolMessageType('PBFuseItemPreference', (_message.Message,), dict(
  DESCRIPTOR = _PBFUSEITEMPREFERENCE,
  __module__ = 'PBFusePreferences_pb2'
  # @@protoc_insertion_point(class_scope:PBFuseItemPreference)
  ))
_sym_db.RegisterMessage(PBFuseItemPreference)


# @@protoc_insertion_point(module_scope)
